# ---- General Configuration ---- #
spring.application.name=TheCommonRoom

# ---- API | TheMovieDB ---- #
themoviedb.api.key=aded8885cfe0777718228cb511a491e7
themoviedb.api.base-url=https://api.themoviedb.org/3

# --- Database Configuration (MySQL) --- #
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- JWT Configuration --- #
# Clave secreta usada para firmar los tokens
application.security.jwt.secret-key=${JWT_SECRET_KEY}

# Expiración del access token -> 1 día (milisegundos)
application.security.jwt.expiration=86400000

# Expiración del refresh token -> 7 días (milisegundos)
# Permite generar un nuevo access token sin que el usuario vuelva a iniciar sesión
application.security.jwt.refresh-token.expiration=604800000

# --- Spring Security Configuration --- #
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

# --- Error Handling Configuration --- #
server.error.whitelabel.enabled=false
server.error.path=/error

# --- Swagger Configuration --- #
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
#springdoc.swagger-ui.path=/swagger-ui.html
